### PR TITLE
Additional posts

### PR DESCRIPTION
**Pull request by jjcav84**
added additional blog posts from jjcav84/additional-posts

### CODE REVIEW

**Comment by jjcav84** [comment]
added additional blog posts from jjcav84/additional-posts

**Comment by jruedas1** [comment]
Thank you so much Jake!

**Comment by jruedas1** [comment]
Quoting from the insights tab:

Excluding merges, 6 authors have pushed 74 commits to master and 74 commits to all branches. On master, 95 files have changed and there have been 40,239 additions and 119 deletions.

**Comment by jjcav84** [comment]
Thank you.  I think I have brought it to a point where it can now simply be maintained as blog content is created.

**Pull request merged**
